ecommerce/ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("products.urls")),
    path('', include("otp_auth.urls")),

]\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/otp_auth/urls.py
from django.urls import path
from .views import register, login_otp, otp, resend_otp, HomePageView
urlpatterns = [
    path('register/', register, name="register"),
    path('login/', login_otp, name="login_with_otp"),
    path('otp', otp, name="otp"),
    path('resend-otp', resend_otp, name="resend_otp"),
    path('home', HomePageView.as_view(), name="home"),
]

ecommerce/products/urls.py
from django.urls import path
from graphene_django.views import GraphQLView

app_name = "app"

urlpatterns = [
    path("graphql/", GraphQLView.as_view(graphiql=True), name="graphql"),
]

ecommerce/otp_auth/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=20)
    otp = models.CharField(max_length=6)
    resend_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.email)

ecommerce/products/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


# class UserOTP(models.Model):
#     """
#     storing user otp in database.
#     after three invalid otp attempt will be expired your otp
#     """
#
#     user = models.ForeignKey(User, related_name="user_otp", on_delete=models.CASCADE)
#     otp = models.IntegerField(blank=True, null=True)
#     invalid_attempt = models.IntegerField(default=0)
#     is_expired = models.BooleanField(default=False)
#
#     def __str__(self):
#         return str(self.user.username)


class Category(models.Model):
    name = models.CharField(max_length=225, unique=True)

    def __str__(self):
        return str(self.name)


class Brand(models.Model):
    name = models.CharField(max_length=225, unique=True)

    def __str__(self):
        return str(self.name)


class Product(models.Model):
    name = models.CharField(max_length=225)
    category = models.ForeignKey(
        Category, related_name="category", on_delete=models.CASCADE
    )
    brand = models.ForeignKey(Brand, related_name="brand", on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    qty = models.IntegerField(default=1)
    image = models.ImageField(upload_to="products/")

    def __str__(self):
        return str(self.name)


class Order(models.Model):

    name = models.CharField(max_length=255)
    products = models.ManyToManyField(Product, related_name="items")
    placed = models.BooleanField(default=False)
    total_price = models.DecimalField(
        blank=True, null=True, max_digits=10, decimal_places=2
    )
    total_qty = models.IntegerField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)

ecommerce/otp_auth/views.py
from datetime import datetime
import pyotp
from .models import Profile
import base64
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.views.generic import View, TemplateView
from django.contrib import messages


class generateKey:
    @staticmethod
    def returnValue(phone):
        return str(phone) + str(datetime.date(datetime.now())) + "Some Random Secret Key"


def register(request):
    if request.method == 'POST':
        email = request.POST.get('email')

        check_user = User.objects.filter(email=email).first()

        if check_user:
            context = {'message': 'User already exists', 'class': 'danger'}
            return render(request, 'register.html', context)

        user, created = User.objects.get_or_create(email=email)
        user.save()
        keygen = generateKey()
        key = base64.b32encode(keygen.returnValue(email).encode())
        otp = pyotp.HOTP(key)
        abc = otp.at(0)
        print(abc)
        profile = Profile(user=user, email=email, otp=abc)
        profile.save()
        request.session['email'] = email
        return redirect('otp')
    return render(request, 'register.html')


def otp(request):
    email = request.session['email']
    context = {'email': email}
    if request.method == 'POST':
        otp = request.POST.get('otp')
        profile = Profile.objects.filter(email=email).first()

        if otp == profile.otp:
            return redirect(reverse('home'))
        else:
            print('Wrong')
            context = {'message': 'Wrong OTP', 'class': 'danger', 'email': email}
            return render(request, 'otp.html', context)

    return render(request, 'otp.html', context)


def login_otp(request):
    email = request.session['email']
    context = {'email': email}
    if request.method == 'POST':
        otp = request.POST.get('otp')
        profile = Profile.objects.filter(email=email).first()

        if otp == profile.otp:
            user = User.objects.get(id=profile.user.id)
            login(request, user)
            return redirect('home')
        else:
            context = {'message': 'Wrong OTP', 'class': 'danger', 'email': email}
            return render(request, 'otp.html', context)

    return render(request, 'login.html', context)


def resend_otp(request):
    email = request.session['email']
    profile = Profile.objects.filter(email=email).first()
    keygen = generateKey()
    key = base64.b32encode(keygen.returnValue(email).encode())
    otp = pyotp.HOTP(key)
    resend_count = profile.resend_count + 1
    abc = otp.at(resend_count)
    profile.otp = abc
    profile.resend_count = resend_count
    print(abc)
    profile.save()
    return redirect('otp')


class HomePageView(LoginRequiredMixin, TemplateView):
    template_name = "home.html"

ecommerce/products/views.py
from django.shortcuts import render

# Create your views here.

ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>

    {% block content %}

    {% endblock %}


</body>
</html>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>-->
<!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>-->

<!--<script language="JavaScript" type="text/javascript" src="/js/jquery-1.2.6.min.js"></script>-->
<!--<script language="JavaScript" type="text/javascript" src="/js/jquery-ui-personalized-1.5.2.packed.js"></script>-->
<!--<script language="JavaScript" type="text/javascript" src="/js/sprinkle.js"></script>-->

<!--<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>-->
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

ecommerce/templates/home.html
{% extends 'base.html' %}

{% block title %} LogicRays {% endblock %}

{% block content %}
	<div class="card container" style="width: 58rem;">
			<div class="card-body">
				<h5 class="card-title">
					WelCome <strong>{{request.user.email}}</strong> To Demo Task logout
				</h5>
                <a href="{% url 'app:graphql' %}">GraphQL</a>
			</div>
	</div>
{% endblock %}

ecommerce/templates/login.html
{% extends "base.html" %}
{% block content %}


<div class="container mt-5 pt-4">

    <div class="col-6 mx-auto">
        <h3 class="text-center">Login</h3>
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-12">
                    <input type="text" placeholder="email" class="form-control" name="email" id="">
                </div>

            </div>
            <p>Don't have account <a href="{% url 'register' %}">Register</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>


{% endblock %}

ecommerce/templates/otp.html
{% extends "base.html" %}
{% block content %}

<div class="container mt-5 pt-4">
    
    <div class="col-6 mx-auto">
        <h3 class="text-center">Enter OTP sent to your email {{email}}</h3>
        {% if message %}
        <div class="alert alert-{{class}}">
            {{message}}
        </div>
        {% endif %}

        <form class="mt-2" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-12 mt-3">
                    <input type="text" placeholder="Enter otp" class="form-control" name="otp" id="">
                </div>
            </div>

            <p>Don't have account <a href="{% url 'register' %}">Register</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
        <a href="{% url 'resend_otp' %}">Resend_otp.</a>
    </div>

</div>


{% endblock %}

ecommerce/templates/register.html
{% extends "base.html" %}
{% block content %}

<div class="container mt-5 pt-4">

    <div class="col-6 mx-auto">
        <h3 class="text-center">Register</h3>
        <form method="post">
            {% csrf_token %}

            {% if message %}
            <div class="alert alert-{{class}}">
                {{message}}
            </div>
            {% endif %}

            <div class="row">
                <div class="form-group col-12">
                    <input type="text" placeholder="Email" class="form-control" name="email" id="">
                </div>
            </div>
            <p>Already have account <a href="{% url 'login_with_otp' %}">Login</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>


{% endblock %}